account/urls.py
# coding: utf-8
""" Module managing urls of
account APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path('connexion/', views.connexion, name='connexion'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path(
        'account_creation/',
        views.account_creation, name='account_creation'),
    path(
        'modify_account/',
        views.modify_account, name='modify_account'),
    path(
        'delete_confirmation/',
        views.delete_confirmation, name='delete_confirmation'),
]

condorvote_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from common import views


urlpatterns = [
    # urls for APPs
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path(
        'command/',
        include(('command.urls', 'app_name'), namespace='command')),
    path(
        'common/',
        include(('common.urls', 'app_name'), namespace='common')),
    path(
        'desk/',
        include(('desk.urls', 'app_name'), namespace='desk')),
    path(
        'documentation/',
        include(('documentation.urls', 'app_name'), namespace='documentation')),
    path(
        'vote/',
        include(('vote.urls', 'app_name'), namespace='vote')),
    path(
        'result/',
        include(('result.urls', 'app_name'), namespace='result')),
    path(
        'account/',
        include(('account.urls', 'app_name'), namespace='account')),
    path(
        'account/',
        include(('django.contrib.auth.urls', 'app_name'), namespace='author')),
    
    # urls for changing password
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'),
        name='password_change_done'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/password_change.html'),
        name='password_change'),

    # urls for reseting password
    path(
        'account/password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset.html'),
        name="password_reset"),
    path(
        'account/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    path(
        'account/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'),
        name="password_reset_confirm"),
    path(
        'account/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'),
        name="password_reset_complete")
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(
            r'^__debug__/',
            include(
                debug_toolbar.urls,
                namespace='debug_toolbar')),
    ] + urlpatterns

desk/urls.py
# coding: utf-8
""" Module managing urls of
account APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path(
        'create_desk/',
        views.create_desk,
        name='create_desk'),
    path(
        'add_candidates/<desk_id>/',
        views.add_candidates,
        name='add_candidates'),
    path(
        'create_tickets/<desk_id>/',
        views.create_tickets,
        name='create_tickets'),
    path(
        'open_desk/<desk_id>/',
        views.open_desk,
        name='open_desk'),
    path(
        'close_desk/<desk_id>/',
        views.close_desk,
        name='close_desk'),
    path(
        'delete_desk/<desk_id>/',
        views.delete_desk,
        name='delete_desk'),
    path(
        'delete_candidate/<candidate_id>/<desk_id>/',
        views.delete_candidate,
        name='delete_candidate'),
    path(
        'add_voters/<desk_id>/',
        views.add_voters,
        name='add_voters'),
    path(
        'display_desk_list/',
        views.display_desk_list,
        name='display_desk_list'),
    path(
        'display_active_desk/<desk_id>/',
        views.display_active_desk,
        name='display_active_desk'),
]

result/urls.py
# coding: utf-8
""" Module managing urls of
result APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path('result//<desk_id>/', views.result, name='result'),
    path(
        'result_details//<desk_id>/',
        views.result_details,
        name='result_details'),
]

desk/forms.py
# coding: utf-8
"""Create formular for Desk
templates and views.
"""
from django import forms

CHOICES = [('1', 'Oui'), ('2', 'Non')]


class DeskCreationForm(forms.Form):
    """Formular Class Form.
    Used in account templates and views for Desk creation.
    """
    school = forms.CharField(label="Etablissement:", max_length=75)
    school_class = forms.CharField(
        label="Nom du bureau de vote: ",
        max_length=75
    )
    tickets_amount = forms.IntegerField(label="Nombre d'électeur:     ")
    opening_vote = forms.ChoiceField(
        label="Ouvrir le bureau maintenant: ",
        widget=forms.RadioSelect, choices=CHOICES
    )


class AddCandidateForm(forms.Form):
    """Formular Class Form.
    Used in account templates and views for adding candidates to desk.
    """
    first_name = forms.CharField(label="Prénom:", max_length=75)
    last_name = forms.CharField(label="Nom: ", max_length=75)


class AddVotersForm(forms.Form):
    """Formular Class Form.
    Used in account templates and views for adding voters to an
    existing desk.
    """
    tickets_amount = forms.IntegerField(
        label="Nouveau nombre d'électeurs:     ")

desk/views.py
# coding: utf-8
"""Run the views for Desk APP.
Views:
-create_desk(request)
-vote(request)
-enter_ticket(request)
"""
import random
import string
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from desk.models import Desk, Ticket, Candidate
from desk.forms import DeskCreationForm, AddCandidateForm, AddVotersForm


@login_required
def create_desk(request):
    """Create a new desk for a connected
    user.
    Arguments:
    -request {GET}
    Returns:
    -template -- create_desk.html
    -context ("form", "new_desk",
        "existing_desk","desk_complete")
    """
    desk_complete = False
    user = request.user
    existing_desk = False
    new_desk_id = None

    if request.method == "POST":
        form = DeskCreationForm(request.POST)
        if form.is_valid():
            school = form.cleaned_data["school"]
            school_class = form.cleaned_data["school_class"]
            tickets_amount = form.cleaned_data["tickets_amount"]
            open_vote = form.cleaned_data["opening_vote"]

            desk_control = Desk.objects.filter(
                school=school,
                school_class=school_class
            )
            if not desk_control:
                new_desk = Desk.objects.create(
                    school=school,
                    school_class=school_class,
                    closing_vote=timezone.now(),
                    opening_vote=timezone.now(),
                    winners="(0,0,0)",
                    number_voters=0,
                    tickets_amount=tickets_amount,
                    status="C"
                )
                if int(open_vote) == 1:
                    new_desk.status = "O"
                    new_desk.save()

                user.account.desk_link.add(new_desk)
                user.account.save()
                new_desk_id = new_desk.id
                desk_complete = True
                return redirect(
                    '/desk/add_candidates/{}/'.format(new_desk.id)
                )
            else:
                old_desk = desk_control[0]
                existing_desk = True
                return redirect(
                    '/desk/add_candidates/{}/'.format(old_desk.id)
                )

    else:
        form = DeskCreationForm()
    context = {
        "form": form,
        "new_desk": new_desk_id,
        "existing_desk": existing_desk,
        "desk_complete": desk_complete,
    }

    return render(request, 'desk/create_desk.html', context)


@login_required
def add_candidates(request, desk_id):
    """Add candidates to a specific desk
    for a connected user.
    Arguments:
    -request {GET}
    -desk_id {int}
    Returns:
    -template -- desk/add_candidates.html
    -context {"form", "double_candidate",
        "adding_candidate", "new_candidate",
        "desk_id","number_candidate"}
    """
    adding_candidate = False
    double_candidate = False
    new_candidate = None
    desk = get_object_or_404(Desk, id=desk_id)

    if request.method == "POST":
        form = AddCandidateForm(request.POST)
        double_candidate = False

        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]

            candidate_control = Candidate.objects.filter(
                first_name=first_name, last_name=last_name,
                school=desk.school, classroom=desk.school_class)

            if not candidate_control:
                new_candidate = Candidate.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    school=desk.school,
                    classroom=desk.school_class
                )
                new_candidate.save()
                desk.candidates.add(new_candidate)
                desk.save()
                adding_candidate = True
            else:
                new_candidate = candidate_control[0]
                double_candidate = True
                adding_candidate = False

    form = AddCandidateForm()
    number_candidates = len(Candidate.objects.all().filter(desk=desk))

    context = {
        "form": form,
        "double_candidate": double_candidate,
        "adding_candidate": adding_candidate,
        "new_candidate": new_candidate,
        "desk_id": desk_id,
        "number_candidate": number_candidates,
    }
    return render(request, 'command/add_candidates.html', context)


@login_required
def create_tickets(request, desk_id):
    """Create a specifif amount of tickets for
    a specific desk. Need a connected user.
    Arguments:
    -request {GET}
    -desk_id {int}
    Returns:
    -template -- desk/create_tickets.html
    -context {"desk", "tickets_list", "existing_tickets",
        "zero_ticket", "to_much_tickets"}
    """
    desk = get_object_or_404(Desk, id=desk_id)
    existing_tickets = len(Ticket.objects.filter(desk_tickets=desk))
    zero_ticket = False
    to_much_tickets = False
    ticket_number = 0
    tickets_list = []

    if existing_tickets == 0:
        for ticket in range(desk.tickets_amount):
            ticket_number += 1
            base_ticket_code = "".join(
                random.choices(
                    string.ascii_letters + string.digits,
                    k=12
                )
            )

            new_ticket = Ticket.objects.create(
                ticket_number=ticket_number,
                ticket_code="".join(
                    [
                        base_ticket_code,
                        str(ticket_number),
                        str(desk_id)
                    ]
                ),
                desk_tickets=desk
            )
            new_ticket.save()
            tickets_list.append(new_ticket)
            existing_tickets = len(
                Ticket.objects.all().filter(desk_tickets=desk)
            )
    else:
        tickets_list = Ticket.objects.all().filter(desk_tickets=desk)

    context = {
        "desk": desk,
        "tickets_list": tickets_list,
        "existing_tickets": existing_tickets,
        "zero_ticket": zero_ticket,
        "to_much_tickets": to_much_tickets,
    }
    return render(request, 'desk/create_tickets.html', context)


@login_required
def display_desk_list(request):
    """Display an ordered list of the user's
    desks. Need a loged user.
    Arguments:
    -request {GET}
    Returns:
    -template -- desk/display_desk_list.html
    -context {desk_list_c", "desk_list_o",
        "desk_list_e", "desk_number"}
    """
    user = request.user
    desk_list = Desk.objects.filter(account=user.account.id)

    context = {
        "desk_list": desk_list,
        "desk_number": len(desk_list),
    }
    return render(request, 'desk/display_desk_list.html', context)


@login_required
def delete_desk(request, desk_id):
    """Delete a specific desk of a connected user.
    Arguments:
    -request {GET}
    -desk_id {int}
    Returns:
    -template -- desk/display_desk_list.html
    -context {"desk_school", "desck_school_class"}
    """
    desk = Desk.objects.filter(id=desk_id)
    if desk:
        desk = desk[0]
        desk.delete()

    user = request.user
    desk_list = Desk.objects.filter(account=user.account.id)

    context = {
        "desk_list": desk_list,
        "desk_number": len(desk_list),
        "message": "Le bureau de vote a bien été supprimé!",
    }
    return render(request, 'desk/display_desk_list.html', context)


@login_required
def open_desk(request, desk_id):
    """Open a created unopend desk to voters.
    Need a connected user.
    Arguments:
    -request {GET}
    -desk_id {int}
    Returns:
    -template -- desk/display_desk_list.html
    -context {""desk_list_c": desk_list_c,
        "desk_list_o", "desk_list_e", "desk_number""}
    """
    desk = get_object_or_404(Desk, id=desk_id)
    if desk.status == "C":
        desk.status = "O"
        desk.opening_vote = timezone.now()
        desk.save()

    user = request.user
    desk_list = Desk.objects.filter(account=user.account.id)

    context = {
        "desk_list": desk_list,
        "desk_number": len(desk_list),
        "desk_status": desk.status,
    }
    return render(request, 'desk/display_desk_list.html', context, )


@login_required
def close_desk(request, desk_id):
    """Close an opened desk to voters.
    Need a connected user.
    Arguments:
    -request {GET}
    -desk_id {int}
    Returns:
    -template -- desk/display_desk_list.html
    -context {""desk_list_c": desk_list_c,
        "desk_list_o", "desk_list_e", "desk_number""}
    """
    desk = get_object_or_404(Desk, id=desk_id)
    if desk.status == "O":
        desk.status = "E"
        desk.closing_vote = timezone.now()
        desk.save()

    user = request.user
    desk_list = Desk.objects.filter(account=user.account.id)

    context = {
        "desk_list": desk_list,
        "desk_number": len(desk_list),
        "desk_status": desk.status,
    }
    return render(request, 'desk/display_desk_list.html', context)


@login_required
def display_active_desk(request, desk_id):
    """Displays all details of a specific desk.
    Need a connected user.
    Arguments:
    -request {GET}
    -desk_id {int}
    Returns:
    -template -- desk/display_active_desk.html
    -context {"desk": desk, "winners", "status",
        "tickets_list", "candidates_list"}
    """
    desk = get_object_or_404(Desk, id=desk_id)
    candidates_list = Candidate.objects.filter(desk=desk_id)
    tickets_list = Ticket.objects.filter(desk_tickets=desk_id)
    winners = desk.winners

    if desk.status == "C":
        status = "Créé/Non ouvert"
    elif desk.status == "O":
        status = "Ouvert"
    elif desk.status == "E":
        status = "clôturé"

    context = {
        "desk": desk,
        "winners": winners,
        "status": status,
        "tickets_list": tickets_list,

desk/templates/desk/add_candidates.html
{% extends 'common/base2.html' %}
{% load static %}

{% block content %}<section id="hero">
    <div class="hero-container" data-aos="fade-up">
        <h1><br/><br/>Ajouter les candidats</h1>
        <article class="container col-lg-12">
            <br/><br/>
        {% if adding_candidate %}
        <h2>Le candidat {{new_candidate.first_name}} {{new_candidate.last_name}} a bien été ajouté<br/></h2>
        {% endif %}

        {% if double_candidate %}
        <h2>Erreur: Le candidat {{new_candidate.first_name}} {{new_candidate.last_name}} a déjà été ajouté<br/></h2>
        {% endif %}

        <h2>Votre bureau compte actuellement {{number_candidate}} candidats</h2>
        <div class="row col-lg-12 services">
            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                <div class="icon-box" data-aos="fade-up">
                    <div class="icon"><i class="bx bx-walk"></i></div>
                    <h4 class="title" "><strong>1/3 Créer le bureau de vote.</strong></h4>
                    <h4 class="title style="background-color: blue;">2/3 Ajouter les candidats.</h4>
                    <h4 class="title">3/3 Récupérer les tickets électeurs.</h4>
                    <p class="description">Ajoutez les candidats de votre élection.<br/>
                        Vous pourrez les modifier ultérieurement si votre bureau n'est pas ouvert au vote.</p>
                </div>
                </div>
            <div class='col-md-12 col-lg-6 '>
                <form class="form1" method="post" action=".">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="about-btn3" type="submit" value="Ajouter"  />
                </form>
            </div>
        <br/><br/>
        <button class="about-btn2" id="end_add">
            <a id="end_add_candidate" style="color:black" href="{% url 'desk:create_tickets' desk_id=desk_id %}">J'ai fini d'ajouter des candidats</a>
        </button>
        <br/><br/>
        </article>
    </div>
</section>{% endblock %}

{% block script %}<script src="{% static 'desk/assets/js/formular_cand.js' %}"></script>
{% endblock %}

desk/templates/desk/display_active_desk.html
{% extends 'common/base2.html' %}
{% load static %}


{% block links %}<link href="{% static 'desk/assets/css/formular_cand.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}<section class="cta">
    <div class="text-center">
        <h1><br/>Bureaux de vote:&emsp;{{desk.school_class}}</h1>
        <br/><br/>
    </div>
    <div class="row" data-aos="fade-up">
        <article class="container d-flex flex-column col-md-10 col-lg-5 frame1">
            <div class="section-title" data-aos="fade-in" data-aos-delay="100">
                <h2><br/>Etat du bureau<br/><br/></h2>
            </div>
            <div class="text-left"><p class="section-title2"></p>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Etablissement</div><p class="col-lg-4">{{desk.school}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Nom du bureau</div><p class="col-lg-4">{{desk.school_class}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Status</div><p class="col-lg-4">{{status}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Nombre d'électeurs</div><p class="col-lg-4">{{desk.tickets_amount}}</p></div>
                {% if desk.status == "C" %}
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Date de création</div><p class="col-lg-4">{{desk.opening_vote}}</p></div>
                {% endif %}
                {% if desk.status == "O" %}
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Date d'ouverture</div><p class="col-lg-4">{{desk.opening_vote}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Bulletins déposés</div><p class="col-lg-4">{{desk.number_voters}}</p></div>
                {% endif %}
                {% if desk.status == "E" %}
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Date d'ouverture</div><p class="col-lg-4">{{desk.opening_vote}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Date de clôture</div><p class="col-lg-4">{{desk.closing_vote}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Bulletins déposés</div><p class="col-lg-4">{{desk.number_voters}}</p></div>
                <div class="row d-flex justify-content-start"><div class="about-info2 col-lg-4">Vainqueur(s)</div><p class="col-lg-4">{{winners}}</p></div>
                <div class="row d-flex justify-content-center"><button class="about-btn2" id="end_add">
                    <a style="color:black" href="{% url 'result:result_details' desk_id=desk.id %}">Résultats détaillés</a>
                </button></div>
                {% endif %}
                <br/><br/>
            </div>
        </article>

        <article class="container d-flex flex-column col-md-10 col-lg-5 frame1">
            <div class="section-title" data-aos="fade-in" data-aos-delay="100">
                <h2><br/>Liste des candidats<br/><br/></h2>
            </div>
            <ul id="cand_list">
            {% for candidate in candidates_list %}
            <li class="text-center" style="list-style-type: none;">
                <div class="col-lg-12">
                <div class="icon-boxes d-flex flex-column justify-content-center">
                    <div class="col-flg-12 icon-box row" data-aos="fade-up" data-aos-delay="100">
                        <h4><i class="bx bx-face"></i>| Nom: {{candidate.first_name}} / Prénom: {{candidate.last_name}}</h4>   
                    </div>
                    <div class="col-flg-12 icon-box row" data-aos="fade-up" data-aos-delay="100">
                        <h4><i class="bx bx-list-ol"></i>| Numéro du candidat: {{candidate.id}}</h4>
                    </div>
                    {% if desk.status == "C" %}
                    <button class="about-btn2 col-lg-6" id="end_add">
                        <a style="color:black" href="{% url 'desk:delete_candidate' candidate_id=candidate.id desk_id=desk.id %}">Supprimer le candidats</a>
                    </button>
                    {% endif %}
                </div>
                <br/><br/><br/>
            </li>
            {% endfor %}
            </ul>
            {% if desk.status == "C" %}
                {% include 'desk/formular_cand.html' %}
            {% endif %}
            <br/><br/>
        </article>
    </div>
    <br/><br/>

    <div class="row">
    <article class="container d-flex flex-column col-lg-9 col-md-12 frame1">
        <div class="section-title" data-aos="fade-in" data-aos-delay="100">
            <h2><br/>Modifier le bureau<br/><br/></h2>
        </div>
        <div class="d-flex justify-content-around"> 
            {% if desk.status == "C" %}
            <button class="about-btn2 col-lg-2 col-md-6">
                <a style="color:black" href="{% url 'desk:add_voters' desk_id=desk.id %}">Modifier le nombre d'électeurs</a>
            </button>
            <button class="about-btn2 col-lg-2 col-md-6">
                <a style="color:black" href="{% url 'desk:open_desk' desk_id=desk.id %}">Ouvrir le bureau</a>
            </button>
            {% endif %}
            {% if desk.status == "O" %}
            <button class="about-btn2">
                <a style="color:black" href="{% url 'desk:close_desk' desk_id=desk.id %}">Clôturer des candidats</a>
            </button>
            {% endif %}
            <button class="about-btn4 col-lg-2 col-md-6" id="end_add">
                <a style="color:black" href="{% url 'desk:delete_desk' desk_id=desk.id %}">Supprimer le bureau</a>
            </button>  
        </div>
        <br/><br/>
    </article>

    {% if desk.status == "C" %}
    <div class="form_tk col-lg-2 col-md-10">
        {% include 'desk/formular_tickets.html' %}
    </div>
    {% endif %}
    </div>
    <br/><br/>

    <article class="container d-flex flex-column col-lg-10 frame2">
        <div class="section-title" data-aos="fade-in" data-aos-delay="100">
            <h2><br/>Tickets restants du bureau : {{remaining_tickets}}/{{desk.tickets_amount}}</h2>
        </div>
        <div class="d-flex justify-content-center">
            <h1 class="hide_tickets col-lg-1"><i class="bx bx-chevrons-down"></i></h1>
        </div><br/>
        
        <ul id="ul_tickets" class="hidden text-center">
            {% for ticket in tickets_list %}
            <li class="col-lg-12">
                <div class="col-lg-6"></div>
                <div class="icon-boxes d-flex flex-column justify-content-center">
                    <div class="col-flg-12 icon-box row" data-aos="fade-up" data-aos-delay="100">
                        <h4><i class="bx bx-tag"></i>| Numéro: {{ticket.ticket_number}} / Code: {{ticket.ticket_code}}</h4>   
                    </div>
                </div>
                <br/><br/><br/>
            </li>
            {% endfor %}
        </ul>
        <br/><br/>
    </article>
</section>
{% endblock %}


{% block script %}<script src="{% static 'desk/assets/js/formular_cand.js' %}"></script>
{% endblock %}

desk/templates/desk/display_desk_list.html
{% extends 'common/base2.html' %}


{% block content %}<section class="cta">
    <div class="text-center" data-aos="fade-up">
        <h1><br/>Mes bureaux de vote</h1>
        <h3><br/>Vous disposez de {{desk_number}} bureau(x) de vote.<br/><br/></h3>
        <h2 class="text-warning">{{message}}</h2>
        <article class="row col-lg-12">      
            
            <div class="frame2 col-md-10 col-lg-4">
                <h2><br/>Bureaux non ouverts</h2>
                {% for desk in desk_list %}
                    {% if desk.status == "C" %}
                    <section id="services2" class="services2">
                        <a href="{% url 'desk:display_active_desk' desk_id=desk.id %}"><div class="container">
                            <div class="d-flex row justify-content-center">
                                <div class="col-lg-11">
                                    <div class="icon-box create" data-aos="fade-up">
                                        <div class="icon">
                                            <i class="bx bx-upload"></i>
                                        </div>
                                        <h4 class="title"><a href="">Etablissement: {{desk.school}}</a></h4>
                                        <h4 class="title">Nom du bureau: {{desk.school_class}}</h4>
                                        <button class="about-btn2">
                                            <a style="color:black" href="{% url 'desk:open_desk' desk_id=desk.id %}">Ouvrir le bureau</a>
                                        </button>
                                        <button class="col-lg-10 about-btn4">
                                            <p><a style="color:black" href="{% url 'desk:delete_desk' desk_id=desk.id %}"><br/>Supprimer le bureau</a></p>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div></a>
                    </section>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="frame2 col-md-10 col-lg-4">
                <h2><br/>Bureaux ouverts</h2>
                {% for desk in desk_list %}
                    {% if desk.status == "O" %}
                    <section id="services2" class="services2">
                        <a href="{% url 'desk:display_active_desk' desk_id=desk.id %}"><div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-12 d-flex align-items-stretch mb-5 mb-lg-0">
                                    <div class="icon-box open" data-aos="fade-up">
                                        <div class="icon">
                                            <i class="bx bx-door-open"></i>
                                        </div>
                                        <h4 class="title"><a href="">Etablissement: {{desk.school}}</a></h4>
                                        <h4 class="title">Nom du bureau: {{desk.school_class}}</h4>
                                        <button class="about-btn2">
                                            <a style="color:black" href="{% url 'desk:close_desk' desk_id=desk.id %}">Clôturer le bureau</a>
                                        </button>
                                        <button class="col-lg-10 about-btn4">
                                            <p><a style="color:black" href="{% url 'desk:delete_desk' desk_id=desk.id %}"><br/>Supprimer le bureau</a></p>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div></a>
                    </section>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="frame2 col-md-10  col-lg-4">
                <h2><br/>Bureaux clôturés</h2>
                {% for desk in desk_list %}
                    {% if desk.status == "E" %}
                    <section id="services2" class="services2 ">
                        <a href="{% url 'desk:display_active_desk' desk_id=desk.id %}"><div class="container">
                            <div class="d-flex row justify-content-center">
                                <div class="col-lg-11">
                                    <div class="icon-box close" data-aos="fade-up">
                                        <div class="icon">
                                            <i class="bx bx-fingerprint"></i>
                                        </div>
                                        <h4 class="title"><a href="">Etablissement: {{desk.school}}</a></h4>
                                        <h4 class="title">Nom du bureau: {{desk.school_class}}</h4>
                                        <button class="about-btn2" >
                                            <a style="color:black" href="{% url 'result:result' desk_id=desk.id %}">Résultats</a>
                                        </button>
                                        <button class="col-lg-10 about-btn4">
                                            <p><a style="color:black" href="{% url 'desk:delete_desk' desk_id=desk.id %}"><br/>Supprimer le bureau</a></p>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div></a>
                    </section>
                    {% endif %}
                {% endfor %}
            </div>

        </article>
    </div>
</section>
{% endblock %}