account/urls.py
# coding: utf-8
""" Module managing urls of
account APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path('connexion/', views.connexion, name='connexion'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path(
        'account_creation/',
        views.account_creation, name='account_creation'),
    path(
        'modify_account/',
        views.modify_account, name='modify_account'),
    path(
        'delete_confirmation/',
        views.delete_confirmation, name='delete_confirmation'),
]

common/urls.py
# coding: utf-8
""" Module managing urls of
common APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path('legal_mentions/', views.legal_mentions, name='legal_mentions'),
    path('error400/', views.error400, name='error400'),
    path('error500/', views.error400, name='error500'),
    path('error404/', views.error400, name='error404'),
]

condorvote_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from common import views


urlpatterns = [
    # urls for APPs
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path(
        'command/',
        include(('command.urls', 'app_name'), namespace='command')),
    path(
        'common/',
        include(('common.urls', 'app_name'), namespace='common')),
    path(
        'desk/',
        include(('desk.urls', 'app_name'), namespace='desk')),
    path(
        'documentation/',
        include(('documentation.urls', 'app_name'), namespace='documentation')),
    path(
        'vote/',
        include(('vote.urls', 'app_name'), namespace='vote')),
    path(
        'result/',
        include(('result.urls', 'app_name'), namespace='result')),
    path(
        'account/',
        include(('account.urls', 'app_name'), namespace='account')),
    path(
        'account/',
        include(('django.contrib.auth.urls', 'app_name'), namespace='author')),
    
    # urls for changing password
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'),
        name='password_change_done'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/password_change.html'),
        name='password_change'),

    # urls for reseting password
    path(
        'account/password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset.html'),
        name="password_reset"),
    path(
        'account/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    path(
        'account/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'),
        name="password_reset_confirm"),
    path(
        'account/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'),
        name="password_reset_complete")
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(
            r'^__debug__/',
            include(
                debug_toolbar.urls,
                namespace='debug_toolbar')),
    ] + urlpatterns

desk/urls.py
# coding: utf-8
""" Module managing urls of
account APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path(
        'create_desk/',
        views.create_desk,
        name='create_desk'),
    path(
        'add_candidates/<desk_id>/',
        views.add_candidates,
        name='add_candidates'),
    path(
        'create_tickets/<desk_id>/',
        views.create_tickets,
        name='create_tickets'),
    path(
        'open_desk/<desk_id>/',
        views.open_desk,
        name='open_desk'),
    path(
        'close_desk/<desk_id>/',
        views.close_desk,
        name='close_desk'),
    path(
        'delete_desk/<desk_id>/',
        views.delete_desk,
        name='delete_desk'),
    path(
        'delete_candidate/<candidate_id>/<desk_id>/',
        views.delete_candidate,
        name='delete_candidate'),
    path(
        'add_voters/<desk_id>/',
        views.add_voters,
        name='add_voters'),
    path(
        'display_desk_list/',
        views.display_desk_list,
        name='display_desk_list'),
    path(
        'display_active_desk/<desk_id>/',
        views.display_active_desk,
        name='display_active_desk'),
]

documentation/urls.py
# coding: utf-8
""" Module managing urls of
documentation APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path('voter_infos/', views.voter_infos, name='voter_infos'),
    path('organizer_infos/', views.organizer_infos, name='organizer_infos'),
    path('condorcet_infos/', views.condorcet_infos, name='condorcet_infos'),
]

vote/urls.py
# coding: utf-8
""" Module managing urls of
vote APP for Django program.
"""
from django.urls import path
from . import views


urlpatterns = [
    path('enter_ticket/', views.enter_ticket, name='enter_ticket'),
    path('vote/<vote_id>/', views.vote, name='vote'),
]

common/views.py
# coding: utf-8
"""Run the views for common APP.
Views:
-index(request)
-legal_mentions(request)
-error400(request)
-error404(request)
-error500(request)
"""
from django.shortcuts import render


def index(request):
    """Front page of web site.
    Arguments:
    -request {GET}
    Returns:
    -template -- index.html
    """
    return render(request, 'common/index.html')


def legal_mentions(request):
    """Rule the legal notice of the website;
    Arguments:
    -request {GET}
    Returns:
    -template -- legal_mentions.html
    """
    return render(request, 'common/legal_mentions.html')


def error400(request):
    """Specific function for testing error templates:
    400.htlm;
    Arguments:
    -request {GET}
    Returns:
    -template -- legal_mentions.html
    """
    return render(request, '400.html')


def error404(request):
    """Specific function for testing error templates:
    404.htlm;
    Arguments:
    -request {GET}
    Returns:
    -template -- legal_mentions.html
    """
    return render(request, '404.html')


def error500(request):
    """Specific function for testing error templates:
    500.htlm;
    Arguments:
    -request {GET}
    Returns:
    -template -- legal_mentions.html
    """
    return render(request, '500.html')

common/templates/common/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>CondorVote</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  {% load static %}<!-- Favicons -->
  <link href="{% static 'common/assets/img/logo.png' %}" rel="icon">
  <link href="{% static 'common/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'common/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'common/assets/css/style.css' %}" rel="stylesheet">
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-transparent">
    <div class="container d-flex align-items-center">

        <div class="row logo mr-auto">
        <a  href="index.html"></a><img id="picture_logo" src="{% static 'common/assets/img/logo.png' %}" alt="" class="img-fluid"></a>
        <h1 class="text-light"><a href="index.html"><span>CondorVote</span></a></h1>
        </div>

        <nav class="nav-menu d-none d-lg-block">
        <ul>
            <li class="active"><a href="{% url 'index' %}">Accueil</a></li>
            {% if user.is_anonymous %}
            <li><a id="connection" href="{% url 'account:connexion' %}">Me connecter</a></li>
            <li><a id="create_account" href="{% url 'account:account_creation' %}">Créer un compte</a></li>
            {% endif %} 
            <li><a id="vote" href="{% url 'vote:enter_ticket' %}">Voter</a></li>
            <li class="drop-down"><a href="">Documentation</a>
            <ul>
                <li><a href="{% url 'documentation:condorcet_infos' %}">Le scrutin de Condorcet</a></li>
                <li><a href="{% url 'documentation:voter_infos' %}">Comment voter</a></li>
                <li><a href="{% url 'documentation:organizer_infos' %}">Créer un bureau de vote</a></li>
            </ul>
            </li>
            {% if user.is_authenticated %}
            <li><a id="create_desk" href="{% url 'desk:create_desk' %}">Créer une élection</a></li>
            <li><a id="connection" href="{% url 'account:deconnexion' %}">Me déconnecter</a></li>
            <li><a id="my_account" href="{% url 'account:myaccount' %}">Mon compte</a></li>
            {% endif %} 
           

        </ul>
        </nav><!-- .nav-menu -->

    </div>
    </header><!-- End Header -->

    {% block contentUp %}
    {% endblock %}

    <main id="main">

    {% block content %}
    {% endblock %}

    <!-- ======= Documentation Section ======= -->
    <section id="services" class="services">
        <div class="container">

        <div class="section-title" data-aos="fade-in" data-aos-delay="100">
            <h2>Documentation</h2>
            <p>Sélectionnez l'une des catégories ci dessous pour plus d'informations.</p>
        </div>

        <div class="row">
            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up">
                <div class="icon"><i class="bx bx-calculator"></i></div>
                <h4 class="title"><a href="{% url 'documentation:condorcet_infos' %}">Le scrutin de Condorcet</a></h4>
                <p class="description">Principes du scrutin de Condorcet et liens utiles</p>
            </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                <div class="icon"><i class="bx bx-file"></i></div>
                <h4 class="title"><a href="{% url 'documentation:voter_infos' %}">Voter?</a></h4>
                <p class="description">Vous avez un ticket de vote et vous ne savez pas comment l'utiliser pour voter? Cliquez ici.</p>
            </div>
            </div>


            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
                <div class="icon"><i class="bx bx-desktop"></i></div>
                <h4 class="title"><a href="{% url 'documentation:organizer_infos' %}">Créer un bureau de vote.</a></h4>
                <p class="description">Vous voulez créer des bureaux de votes pour vos classes? Le détail est expliqué dans cette section.</p>
            </div>
            </div>

        </div>

        </div>
    </section><!-- End Services Section -->

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
    <div class="container">
        <div class="copyright">
        &copy; Copyright <strong><span>CondorVote</span></strong>. All Rights Reserved
        </div>
        <div class="credits legal_mentions">
            Mentions légales <a href="{% url 'common:legal_mentions' %}">ici</a>
        </div>
        <div class="credits">
        Designed by <a href="https://github.com/Thibault231/CondorVote.git">Th231</a>
        </div>
    </div>
    </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'common/assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'common/assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/aos/aos.js' %}"></script>
  

  <!-- Template Main JS File -->
  <script src="{% static 'common/assets/js/main.js' %}"></script>
  {% block javascript %}{% endblock%}
</body>

</html>

common/templates/common/base2.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>CondorVote</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  {% load static %}<!-- Favicons -->
  <link href="{% static 'common/assets/img/logo.png' %}" rel="icon">
  <link href="{% static 'common/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'common/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'common/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  {% block links %}
  {% endblock %}

  <!-- Template Main CSS File -->
  <link href="{% static 'common/assets/css/style.css' %}" rel="stylesheet">
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-transparent">
        <div class="container d-flex align-items-center">
    
            <div class="row logo mr-auto">
            <a href="index.html"></a><img id="picture_logo" src="{% static 'common/assets/img/logo.png' %}" alt="" class="img-fluid"></a>
            <h1 class="text-light"><a href="index.html"><span>CondorVote</span></a></h1>
            </div>
    
            <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="{% url 'index' %}">Accueil</a></li>
                {% if user.is_anonymous %}
                <li><a id="connection" href="{% url 'account:connexion' %}">Me connecter</a></li>
                <li><a id="create_account" href="{% url 'account:account_creation' %}">Créer un compte</a></li>
                {% endif %} 
                <li><a id="vote" href="{% url 'vote:enter_ticket' %}">Voter</a></li>
                <li class="drop-down"><a href="">Documentation</a>
                <ul>
                    <li><a href="{% url 'documentation:condorcet_infos' %}">Le scrutin de Condorcet</a></li>
                    <li><a href="{% url 'documentation:voter_infos' %}">Comment voter</a></li>
                    <li><a id="create_desk" href="{% url 'documentation:organizer_infos' %}">Créer une élection</a></li>
                </ul>
                </li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'desk:create_desk' %}">Créer une élection</a></li>
                <li><a id="connection" href="{% url 'account:deconnexion' %}">Me déconnecter</a></li>
                <li><a id="my_account2" href="{% url 'account:myaccount' %}">Mon compte</a></li>
                {% endif %} 
               
    
            </ul>
            </nav><!-- .nav-menu -->
    
        </div>
    </header><!-- End Header -->

<main id="main">

    {% block content %}
    {% endblock %}

    <!-- ======= Footer ======= -->
    <footer id="footer">
    <div class="container">
        <div class="copyright">
        &copy; Copyright <strong><span>CondorVote</span></strong>. All Rights Reserved
        </div>
        <div class="credits legal_mentions">
            Mentions légales <a href="{% url 'common:legal_mentions' %}">ici</a>
        </div>
        <div class="credits">
        Designed by <a href="https://github.com/Thibault231/CondorVote.git">Th231</a>
        </div>
    </div>
    </footer><!-- End Footer -->
</main>

<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="{% static 'common/assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'common/assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'common/assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'common/assets/js/main.js' %}"></script>
  {% block script %}
  {% endblock %}

</body>

</html>

common/templates/common/index.html
{% extends 'common/base.html' %}  

    {% block contentUp %}
    <!-- ======= Accueil Section ======= -->
    <section id="hero">
    <div class="hero-container" data-aos="fade-up">
        <h1>Bienvenue sur CondorVote</h1>
        <h2>Votez sans plus attendre en cliquant ci-dessous.</h2>
        <a href="#about" class="btn-get-started scrollto"><i class="bx bx-chevrons-down"></i></a>
    </div>
    </section><!-- End Hero -->
    {% endblock %}

    {% block content %}
    <!-- ======= Acceuil-présentation Section ======= -->
    <section id="about" class="about">
        <div class="container">

        <div class="row no-gutters">
            <div class="content col-xl-5 d-flex align-items-stretch" data-aos="fade-up">
            <div class="content">
                <h3>Entrez le numéro de votre ticket ci dessous</h3>
                <p>
                Mon numéro de ticket:
                </p>
                <form action="{% url 'vote:enter_ticket' %}" method="POST">
                    {% csrf_token %}
                    <div class="container">
                        <div class="d-flex flex-column">
                            <input type="text" name="item_name" maxlength="100" class="item_name" id="item_name">
                            <button type="submit" class="about-btn">Je vote <i class="bx bx-message-check"></i></button>
                        </div>
                    </div>
                </form>   
            </div>
            </div>
            <div class="col-xl-7 d-flex align-items-stretch">
            <div class="icon-boxes d-flex flex-column justify-content-center">
                <div class="row">
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                    <i class="bx bx-smile"></i>
                    <h4>SIMPLE</h4>
                    <p>Un site de vote en ligne simple d'utilisation</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                    <i class="bx bx-right-arrow"></i>
                    <h4>SPECIFIQUE</h4>
                    <p>Un site de vote à destination des établissement scolaire</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                    <i class="bx bx-box"></i>
                    <h4>MODULABLE</h4>
                    <p>Créer autant des bureaux de vote adaptés à vos classes</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
                    <i class="bx bx-money"></i>
                    <h4>GRATUIT</h4>
                    <p>CondorVote est un projet opensource. Pas besoin de payer pour voter. Encore heureux!</p>
                </div>
                </div>
            </div><!-- End .content-->
            </div>
        </div>

        </div>
    </section><!-- End About Section -->
    {% endblock %}